import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock000
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock001
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock002
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock003
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock004
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock005
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock006
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock007
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock008
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock009
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock010
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock011
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock012
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock013
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock014
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock015
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock016
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock017
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock018
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock019
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock020
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock021
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock022
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock023
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock024
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock025
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock026
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock027
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock028
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock029
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock030
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock031
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock032
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock033
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock034
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock035
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock036
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock037
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock038
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock039
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock040
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock041
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock042
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock043
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock044
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock045
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock046
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock047
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock048
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock049
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock050
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock051
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock052
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock053
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock054
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock055
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock056
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock057
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock058
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock059
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock060
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock061
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock062
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock063
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock064
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock065
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock066
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock067
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock068
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock069
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock070
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock071
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock072
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock073
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock074
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock075
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock076
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock077
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock078
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock079
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock080
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock081
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock082
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock083
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock084
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock085
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock086
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock087
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock088
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock089
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock090
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock091
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock092
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock093
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock094
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock095
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock096
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock097
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock098
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock099
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock100
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock101
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock102
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock103
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock104
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock105
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock106
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock107
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock108
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock109
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock110
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock111
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock112
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock113
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock114
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock115
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock116
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock117
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock118
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock119
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock120
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock121
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock122
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock123
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock124
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock125
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock126
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock127
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock128
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock129
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock130
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock131
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock132
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock133
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock134
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock135
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock136
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock137
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock138
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock139
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock140
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock141
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock142
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock143
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock144
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock145
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock146
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock147
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock148
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock149
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock150
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock151
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock152
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock153
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock154
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock155
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock156
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock157
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock158
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock159
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock160
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock161
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock162
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock163
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock164
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock165
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock166
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock167
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock168
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock169
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock170
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock171
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock172
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock173
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock174
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock175
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock176
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock177
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock178
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock179
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock180
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock181
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock182
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock183
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock184
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock185
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock186
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock187
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock188
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock189
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock190
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock191
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock192
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock193
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock194
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock195
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock196
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock197
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock198
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock199
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock200
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock201
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock202
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock203
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock204
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock205
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock206
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock207
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock208
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock209
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock210
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock211
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock212
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock213
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock214
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock215
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock216
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock217
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock218
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock219
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock220
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock221
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock222
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock223
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock224
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock225
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock226
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock227
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock228
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock229
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock230
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock231
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock232
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock233
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock234
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock235
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock236
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock237
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock238
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock239
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock240
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock241
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock242
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock243
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock244
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock245
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock246
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock247
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock248
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock249
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock250
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock251
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock252
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock253
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock254
import AiMathLab.P0054MiddleSevenNineFour.MiddleFourClassificationBlock255

namespace AiMathLab.P0054.MiddleSevenNineFinite

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
-- Exhaustive block dispatch covers all fourteen-bit support masks.
theorem middle_four_classification_block_check
    (block : Fin 256) (offset : Fin 64) :
    middleFourClassificationMaskCheck
      (block.val * 64 + offset.val) = true := by
  fin_cases block
  · exact middle_four_classification_block_000 offset
  · exact middle_four_classification_block_001 offset
  · exact middle_four_classification_block_002 offset
  · exact middle_four_classification_block_003 offset
  · exact middle_four_classification_block_004 offset
  · exact middle_four_classification_block_005 offset
  · exact middle_four_classification_block_006 offset
  · exact middle_four_classification_block_007 offset
  · exact middle_four_classification_block_008 offset
  · exact middle_four_classification_block_009 offset
  · exact middle_four_classification_block_010 offset
  · exact middle_four_classification_block_011 offset
  · exact middle_four_classification_block_012 offset
  · exact middle_four_classification_block_013 offset
  · exact middle_four_classification_block_014 offset
  · exact middle_four_classification_block_015 offset
  · exact middle_four_classification_block_016 offset
  · exact middle_four_classification_block_017 offset
  · exact middle_four_classification_block_018 offset
  · exact middle_four_classification_block_019 offset
  · exact middle_four_classification_block_020 offset
  · exact middle_four_classification_block_021 offset
  · exact middle_four_classification_block_022 offset
  · exact middle_four_classification_block_023 offset
  · exact middle_four_classification_block_024 offset
  · exact middle_four_classification_block_025 offset
  · exact middle_four_classification_block_026 offset
  · exact middle_four_classification_block_027 offset
  · exact middle_four_classification_block_028 offset
  · exact middle_four_classification_block_029 offset
  · exact middle_four_classification_block_030 offset
  · exact middle_four_classification_block_031 offset
  · exact middle_four_classification_block_032 offset
  · exact middle_four_classification_block_033 offset
  · exact middle_four_classification_block_034 offset
  · exact middle_four_classification_block_035 offset
  · exact middle_four_classification_block_036 offset
  · exact middle_four_classification_block_037 offset
  · exact middle_four_classification_block_038 offset
  · exact middle_four_classification_block_039 offset
  · exact middle_four_classification_block_040 offset
  · exact middle_four_classification_block_041 offset
  · exact middle_four_classification_block_042 offset
  · exact middle_four_classification_block_043 offset
  · exact middle_four_classification_block_044 offset
  · exact middle_four_classification_block_045 offset
  · exact middle_four_classification_block_046 offset
  · exact middle_four_classification_block_047 offset
  · exact middle_four_classification_block_048 offset
  · exact middle_four_classification_block_049 offset
  · exact middle_four_classification_block_050 offset
  · exact middle_four_classification_block_051 offset
  · exact middle_four_classification_block_052 offset
  · exact middle_four_classification_block_053 offset
  · exact middle_four_classification_block_054 offset
  · exact middle_four_classification_block_055 offset
  · exact middle_four_classification_block_056 offset
  · exact middle_four_classification_block_057 offset
  · exact middle_four_classification_block_058 offset
  · exact middle_four_classification_block_059 offset
  · exact middle_four_classification_block_060 offset
  · exact middle_four_classification_block_061 offset
  · exact middle_four_classification_block_062 offset
  · exact middle_four_classification_block_063 offset
  · exact middle_four_classification_block_064 offset
  · exact middle_four_classification_block_065 offset
  · exact middle_four_classification_block_066 offset
  · exact middle_four_classification_block_067 offset
  · exact middle_four_classification_block_068 offset
  · exact middle_four_classification_block_069 offset
  · exact middle_four_classification_block_070 offset
  · exact middle_four_classification_block_071 offset
  · exact middle_four_classification_block_072 offset
  · exact middle_four_classification_block_073 offset
  · exact middle_four_classification_block_074 offset
  · exact middle_four_classification_block_075 offset
  · exact middle_four_classification_block_076 offset
  · exact middle_four_classification_block_077 offset
  · exact middle_four_classification_block_078 offset
  · exact middle_four_classification_block_079 offset
  · exact middle_four_classification_block_080 offset
  · exact middle_four_classification_block_081 offset
  · exact middle_four_classification_block_082 offset
  · exact middle_four_classification_block_083 offset
  · exact middle_four_classification_block_084 offset
  · exact middle_four_classification_block_085 offset
  · exact middle_four_classification_block_086 offset
  · exact middle_four_classification_block_087 offset
  · exact middle_four_classification_block_088 offset
  · exact middle_four_classification_block_089 offset
  · exact middle_four_classification_block_090 offset
  · exact middle_four_classification_block_091 offset
  · exact middle_four_classification_block_092 offset
  · exact middle_four_classification_block_093 offset
  · exact middle_four_classification_block_094 offset
  · exact middle_four_classification_block_095 offset
  · exact middle_four_classification_block_096 offset
  · exact middle_four_classification_block_097 offset
  · exact middle_four_classification_block_098 offset
  · exact middle_four_classification_block_099 offset
  · exact middle_four_classification_block_100 offset
  · exact middle_four_classification_block_101 offset
  · exact middle_four_classification_block_102 offset
  · exact middle_four_classification_block_103 offset
  · exact middle_four_classification_block_104 offset
  · exact middle_four_classification_block_105 offset
  · exact middle_four_classification_block_106 offset
  · exact middle_four_classification_block_107 offset
  · exact middle_four_classification_block_108 offset
  · exact middle_four_classification_block_109 offset
  · exact middle_four_classification_block_110 offset
  · exact middle_four_classification_block_111 offset
  · exact middle_four_classification_block_112 offset
  · exact middle_four_classification_block_113 offset
  · exact middle_four_classification_block_114 offset
  · exact middle_four_classification_block_115 offset
  · exact middle_four_classification_block_116 offset
  · exact middle_four_classification_block_117 offset
  · exact middle_four_classification_block_118 offset
  · exact middle_four_classification_block_119 offset
  · exact middle_four_classification_block_120 offset
  · exact middle_four_classification_block_121 offset
  · exact middle_four_classification_block_122 offset
  · exact middle_four_classification_block_123 offset
  · exact middle_four_classification_block_124 offset
  · exact middle_four_classification_block_125 offset
  · exact middle_four_classification_block_126 offset
  · exact middle_four_classification_block_127 offset
  · exact middle_four_classification_block_128 offset
  · exact middle_four_classification_block_129 offset
  · exact middle_four_classification_block_130 offset
  · exact middle_four_classification_block_131 offset
  · exact middle_four_classification_block_132 offset
  · exact middle_four_classification_block_133 offset
  · exact middle_four_classification_block_134 offset
  · exact middle_four_classification_block_135 offset
  · exact middle_four_classification_block_136 offset
  · exact middle_four_classification_block_137 offset
  · exact middle_four_classification_block_138 offset
  · exact middle_four_classification_block_139 offset
  · exact middle_four_classification_block_140 offset
  · exact middle_four_classification_block_141 offset
  · exact middle_four_classification_block_142 offset
  · exact middle_four_classification_block_143 offset
  · exact middle_four_classification_block_144 offset
  · exact middle_four_classification_block_145 offset
  · exact middle_four_classification_block_146 offset
  · exact middle_four_classification_block_147 offset
  · exact middle_four_classification_block_148 offset
  · exact middle_four_classification_block_149 offset
  · exact middle_four_classification_block_150 offset
  · exact middle_four_classification_block_151 offset
  · exact middle_four_classification_block_152 offset
  · exact middle_four_classification_block_153 offset
  · exact middle_four_classification_block_154 offset
  · exact middle_four_classification_block_155 offset
  · exact middle_four_classification_block_156 offset
  · exact middle_four_classification_block_157 offset
  · exact middle_four_classification_block_158 offset
  · exact middle_four_classification_block_159 offset
  · exact middle_four_classification_block_160 offset
  · exact middle_four_classification_block_161 offset
  · exact middle_four_classification_block_162 offset
  · exact middle_four_classification_block_163 offset
  · exact middle_four_classification_block_164 offset
  · exact middle_four_classification_block_165 offset
  · exact middle_four_classification_block_166 offset
  · exact middle_four_classification_block_167 offset
  · exact middle_four_classification_block_168 offset
  · exact middle_four_classification_block_169 offset
  · exact middle_four_classification_block_170 offset
  · exact middle_four_classification_block_171 offset
  · exact middle_four_classification_block_172 offset
  · exact middle_four_classification_block_173 offset
  · exact middle_four_classification_block_174 offset
  · exact middle_four_classification_block_175 offset
  · exact middle_four_classification_block_176 offset
  · exact middle_four_classification_block_177 offset
  · exact middle_four_classification_block_178 offset
  · exact middle_four_classification_block_179 offset
  · exact middle_four_classification_block_180 offset
  · exact middle_four_classification_block_181 offset
  · exact middle_four_classification_block_182 offset
  · exact middle_four_classification_block_183 offset
  · exact middle_four_classification_block_184 offset
  · exact middle_four_classification_block_185 offset
  · exact middle_four_classification_block_186 offset
  · exact middle_four_classification_block_187 offset
  · exact middle_four_classification_block_188 offset
  · exact middle_four_classification_block_189 offset
  · exact middle_four_classification_block_190 offset
  · exact middle_four_classification_block_191 offset
  · exact middle_four_classification_block_192 offset
  · exact middle_four_classification_block_193 offset
  · exact middle_four_classification_block_194 offset
  · exact middle_four_classification_block_195 offset
  · exact middle_four_classification_block_196 offset
  · exact middle_four_classification_block_197 offset
  · exact middle_four_classification_block_198 offset
  · exact middle_four_classification_block_199 offset
  · exact middle_four_classification_block_200 offset
  · exact middle_four_classification_block_201 offset
  · exact middle_four_classification_block_202 offset
  · exact middle_four_classification_block_203 offset
  · exact middle_four_classification_block_204 offset
  · exact middle_four_classification_block_205 offset
  · exact middle_four_classification_block_206 offset
  · exact middle_four_classification_block_207 offset
  · exact middle_four_classification_block_208 offset
  · exact middle_four_classification_block_209 offset
  · exact middle_four_classification_block_210 offset
  · exact middle_four_classification_block_211 offset
  · exact middle_four_classification_block_212 offset
  · exact middle_four_classification_block_213 offset
  · exact middle_four_classification_block_214 offset
  · exact middle_four_classification_block_215 offset
  · exact middle_four_classification_block_216 offset
  · exact middle_four_classification_block_217 offset
  · exact middle_four_classification_block_218 offset
  · exact middle_four_classification_block_219 offset
  · exact middle_four_classification_block_220 offset
  · exact middle_four_classification_block_221 offset
  · exact middle_four_classification_block_222 offset
  · exact middle_four_classification_block_223 offset
  · exact middle_four_classification_block_224 offset
  · exact middle_four_classification_block_225 offset
  · exact middle_four_classification_block_226 offset
  · exact middle_four_classification_block_227 offset
  · exact middle_four_classification_block_228 offset
  · exact middle_four_classification_block_229 offset
  · exact middle_four_classification_block_230 offset
  · exact middle_four_classification_block_231 offset
  · exact middle_four_classification_block_232 offset
  · exact middle_four_classification_block_233 offset
  · exact middle_four_classification_block_234 offset
  · exact middle_four_classification_block_235 offset
  · exact middle_four_classification_block_236 offset
  · exact middle_four_classification_block_237 offset
  · exact middle_four_classification_block_238 offset
  · exact middle_four_classification_block_239 offset
  · exact middle_four_classification_block_240 offset
  · exact middle_four_classification_block_241 offset
  · exact middle_four_classification_block_242 offset
  · exact middle_four_classification_block_243 offset
  · exact middle_four_classification_block_244 offset
  · exact middle_four_classification_block_245 offset
  · exact middle_four_classification_block_246 offset
  · exact middle_four_classification_block_247 offset
  · exact middle_four_classification_block_248 offset
  · exact middle_four_classification_block_249 offset
  · exact middle_four_classification_block_250 offset
  · exact middle_four_classification_block_251 offset
  · exact middle_four_classification_block_252 offset
  · exact middle_four_classification_block_253 offset
  · exact middle_four_classification_block_254 offset
  · exact middle_four_classification_block_255 offset

theorem middle_four_classification_mask_check (mask : Fin 16384) :
    middleFourClassificationMaskCheck mask.val = true := by
  let block : Fin 256 :=
    ⟨mask.val / 64, by omega⟩
  let offset : Fin 64 :=
    ⟨mask.val % 64, Nat.mod_lt _ (by omega)⟩
  have hCheck := middle_four_classification_block_check block offset
  simpa [block, offset, Nat.div_add_mod'] using hCheck

theorem middle_four_classification_check :
    (List.range 16384).all middleFourClassificationMaskCheck = true := by
  rw [List.all_eq_true]
  intro mask hMask
  exact middle_four_classification_mask_check
    ⟨mask, List.mem_range.mp hMask⟩

end AiMathLab.P0054.MiddleSevenNineFinite
