"""Generate the frozen Lean witness table for the P0054 size-55 family.

The generator is not trusted for correctness: Lean checks every emitted chain.
This script nevertheless performs its own exact validation before writing the
table, so generation failures are caught early.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from scripts.p0054_verify_candidate import (
    DEFAULT_INPUT,
    candidate_from_record,
    expanded_family,
)

BLOCK_DIRECTORY = Path("AiMathLab/P0054Size55WitnessBlocks")
AGGREGATE_OUTPUT = Path("AiMathLab/P0054Size55WitnessBlocks.lean")
MAIN_OUTPUT = Path("AiMathLab/P0054Size55.lean")
CORE_INPUT = Path("AiMathLab/P0054Size55Core.lean")
MANIFEST_OUTPUT = Path("Problems/P0054/formal/witness-table-manifest.json")


def _paths(
    family: tuple[int, ...],
) -> tuple[dict[int, tuple[int, ...]], dict[int, tuple[int, ...]]]:
    ordered = tuple(sorted(family, key=lambda item: (item.bit_count(), item)))
    path_to: dict[int, tuple[int, ...]] = {}
    for position, member in enumerate(ordered):
        prefixes = [path_to[item] for item in ordered[:position] if item & member == item]
        path_to[member] = (*max(prefixes, key=len, default=()), member)

    path_from: dict[int, tuple[int, ...]] = {}
    for position, member in enumerate(reversed(ordered)):
        larger = tuple(reversed(ordered))[:position]
        suffixes = [path_from[item] for item in larger if member & item == member]
        path_from[member] = (member, *max(suffixes, key=len, default=()))
    return path_to, path_from


def witness_table(family: tuple[int, ...], n: int = 11) -> list[list[int]]:
    """Return descending eight-chain witnesses, with empty rows for members."""

    family_set = set(family)
    path_to, path_from = _paths(family)
    rows: list[list[int]] = []
    for outside in range(1 << n):
        if outside in family_set:
            rows.append([])
            continue
        lower = max(
            (path for member, path in path_to.items() if member & outside == member),
            key=len,
            default=(),
        )
        upper = max(
            (path for member, path in path_from.items() if outside & member == outside),
            key=len,
            default=(),
        )
        ascending = (*lower, outside, *upper)
        if len(ascending) != 8:
            raise AssertionError({"outside": outside, "length": len(ascending)})
        if any(
            left & right != left or left == right
            for left, right in zip(ascending, ascending[1:], strict=False)
        ):
            raise AssertionError({"outside": outside, "chain": ascending})
        if any(member not in family_set for member in (*lower, *upper)):
            raise AssertionError({"outside": outside, "chain_member_outside_family": ascending})
        rows.append(list(reversed(ascending)))
    return rows


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def render_block(block: int, rows: list[list[int]]) -> str:
    label = f"{block:02d}"
    base = 64 * block
    lines = [
        "/- This file is generated by scripts/p0054_generate_lean_witnesses.py. -/",
        "import AiMathLab.P0054Size55Core",
        "",
        "namespace AiMathLab.P0054",
        "",
        "open AiMathLab.SaturatedSperner",
        "",
        "set_option maxRecDepth 100000",
        "",
        f"private def size55WitnessBlock{label} : Array (List Nat) := #[",
    ]
    for index, row in enumerate(rows):
        suffix = "," if index + 1 < len(rows) else ""
        lines.append(f"  {row}{suffix}")
    lines.extend(
        [
            "]",
            "",
            f"private def size55BlockWitness{label} (i : Fin 64) : List Nat :=",
            f"  size55WitnessBlock{label}.getD i.val []",
            "",
            "set_option maxHeartbeats 1000000 in",
            "-- The block is a finite reflection proof over exactly 64 masks.",
            f"private theorem size55_witness_block_{label}_checked :",
            "    ∀ i : Fin 64,",
            f"      let S := maskSubset ({base} + i.val)",
            "      S ∈ size55 ∨",
            "        maskChainWitnessChecker 8 (insert S size55) S",
            f"          (size55BlockWitness{label} i) = true := by",
            "  decide",
            "",
            f"theorem size55_witness_block_{label} (i : Fin 64) :",
            f"    let S := maskSubset ({base} + i.val)",
            "    S ∈ size55 ∨ HasStrictChainLength 8 (insert S size55) := by",
            f"  rcases size55_witness_block_{label}_checked i with h | h",
            "  · exact Or.inl h",
            "  · exact Or.inr <| maskChainWitness_sound <|",
            "      (maskChainWitnessChecker_eq_true 8 _ _ _).mp h",
            "",
            "end AiMathLab.P0054",
            "",
        ]
    )
    return "\n".join(lines)


def render_aggregate() -> str:
    lines = [
        "/- This file is generated by scripts/p0054_generate_lean_witnesses.py. -/",
        *(f"import AiMathLab.P0054Size55WitnessBlocks.Block{block:02d}" for block in range(32)),
        "",
    ]
    return "\n".join(lines)


def render_main() -> str:
    lines = [
        "/-",
        "Copyright (c) 2026 AI Math Lab. All rights reserved.",
        "Released under Apache 2.0 license as described in the file LICENSE.",
        "Authors: Jiazhi Chen",
        "-/",
        "import AiMathLab.P0054Size55WitnessBlocks",
        "",
        "/-! # Kernel-checked certificate for the P0054 size-55 construction -/",
        "",
        "namespace AiMathLab.P0054",
        "",
        "open AiMathLab.SaturatedSperner",
        "",
        "/-- The 32 checked blocks cover every eleven-bit mask. -/",
        "private theorem size55_witness_masks_complete (m : Nat) (hm : m < 2048) :",
        "    let S := maskSubset m",
        "    S ∈ size55 ∨ HasStrictChainLength 8 (insert S size55) := by",
    ]
    for block in range(31):
        label = f"{block:02d}"
        base = 64 * block
        upper = base + 64
        lines.extend(
            [
                f"  by_cases h{label} : m < {upper}",
                f"  · have h := size55_witness_block_{label} ⟨m - {base}, by omega⟩",
                f"    have heq : {base} + (m - {base}) = m := by omega",
                "    simpa only [heq] using h",
            ]
        )
    lines.extend(
        [
            "  have h := size55_witness_block_31 ⟨m - 1984, by omega⟩",
            "  have heq : 1984 + (m - 1984) = m := by omega",
            "  simpa only [heq] using h",
            "",
            "private theorem size55_witnesses_complete :",
            "    ∀ S : GroundSubset,",
            "      S ∈ size55 ∨ HasStrictChainLength 8 (insert S size55) := by",
            "  intro S",
            "  have h := size55_witness_masks_complete",
            "    (subsetMask S) (subsetMask_lt_2048 S)",
            "  simpa only [maskSubset_subsetMask] using h",
            "",
            "/-- The explicit 55-member family is saturated 7-Sperner. -/",
            "theorem size55_saturated : IsSaturatedKSperner 7 size55 := by",
            "  refine ⟨size55_seven_sperner, ?_⟩",
            "  intro S hSF",
            "  exact (size55_witnesses_complete S).resolve_left hSF",
            "",
            "/-- The complete finite certificate for the 55-member construction. -/",
            "theorem size55_full_certificate :",
            "    size55.card = 55 ∧ IsSaturatedKSperner 7 size55 :=",
            "  ⟨size55_card, size55_saturated⟩",
            "",
            "end AiMathLab.P0054",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    source = json.loads(DEFAULT_INPUT.read_text(encoding="utf-8"))
    candidate = candidate_from_record(source)
    family = expanded_family(candidate)
    rows = witness_table(family)
    table_semantic = json.dumps(rows, separators=(",", ":")).encode()
    BLOCK_DIRECTORY.mkdir(parents=True, exist_ok=True)
    block_records: list[dict[str, Any]] = []
    for block in range(32):
        path = BLOCK_DIRECTORY / f"Block{block:02d}.lean"
        block_text = render_block(block, rows[64 * block : 64 * (block + 1)])
        path.write_text(block_text, encoding="utf-8")
        block_records.append({"path": str(path), "sha256": _sha256_bytes(block_text.encode())})
    aggregate_text = render_aggregate()
    main_text = render_main()
    AGGREGATE_OUTPUT.write_text(aggregate_text, encoding="utf-8")
    MAIN_OUTPUT.write_text(main_text, encoding="utf-8")
    manifest: dict[str, Any] = {
        "schema": "ai-math-lab.p0054.lean-witness-table.v2",
        "source_candidate_sha256": source["candidate_sha256"],
        "ground_size": 11,
        "row_count": len(rows),
        "external_witness_count": sum(bool(row) for row in rows),
        "member_row_count": sum(not row for row in rows),
        "witness_length": 8,
        "table_semantic_sha256": _sha256_bytes(table_semantic),
        "block_size": 64,
        "core_path": str(CORE_INPUT),
        "core_sha256": _sha256_bytes(CORE_INPUT.read_bytes()),
        "blocks": block_records,
        "aggregate_path": str(AGGREGATE_OUTPUT),
        "aggregate_sha256": _sha256_bytes(aggregate_text.encode()),
        "main_path": str(MAIN_OUTPUT),
        "main_sha256": _sha256_bytes(main_text.encode()),
    }
    MANIFEST_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_OUTPUT.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
